import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, readdir, rm, writeFile } from "fs/promises";
import { tmpdir } from "os";
import { join, resolve } from "path";
import { createTemporaryDatabase } from "./utils/test-helper";

const cliEntrypoint = resolve(process.cwd(), "cli.ts");

interface CliResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

const decode = async (stream: ReadableStream<Uint8Array> | null) => {
  if (!stream) {
    return "";
  }

  return await new Response(stream).text();
};

const runCli = async (
  args: string[],
  env: Record<string, string>,
  cwd: string
): Promise<CliResult> => {
  const child = Bun.spawn([process.execPath, cliEntrypoint, ...args], {
    cwd,
    env: {
      ...process.env,
      ...env,
    },
    stdout: "pipe",
    stderr: "pipe",
  });

  const [stdout, stderr, exitCode] = await Promise.all([
    decode(child.stdout),
    decode(child.stderr),
    child.exited,
  ]);

  return { exitCode, stdout, stderr };
};

describe("cli smoke test", () => {
  const cleanupPaths: string[] = [];

  afterEach(async () => {
    for (const path of cleanupPaths.splice(0)) {
      await rm(path, { recursive: true, force: true });
    }
  });

  test("create, up, status, and down work against a fresh database", async () => {
    const database = await createTemporaryDatabase("cli_smoke");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-smoke-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);
      expect(createResult.stdout).toContain("Created");
      expect(createResult.stderr).toBe("");

      const createdFiles = await readdir(migrationsPath);
      const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
      const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

      expect(upFile).toBeDefined();
      expect(downFile).toBeDefined();

      await writeFile(
        join(migrationsPath, upFile!),
        `
        CREATE TABLE widgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, downFile!),
        `DROP TABLE IF EXISTS widgets;`
      );

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);
      expect(upResult.stdout).toContain("Executed 1 migration(s)");

      const createdTable = await database.pool.query<{
        regclass: string | null;
      }>(`SELECT to_regclass('public.widgets') AS regclass`);
      expect(createdTable.rows[0]?.regclass).toBe("widgets");

      const statusResult = await runCli(["status"], env, workspace);
      expect(statusResult.exitCode).toBe(0);
      expect(statusResult.stdout).toContain(upFile!);
      expect(statusResult.stdout).toContain("Total: 1 executed, 0 pending");

      const downResult = await runCli(["down", "1"], env, workspace);
      expect(downResult.exitCode).toBe(0);
      expect(downResult.stdout).toContain("Rolled back 1 migration(s)");

      const droppedTable = await database.pool.query<{
        regclass: string | null;
      }>(`SELECT to_regclass('public.widgets') AS regclass`);
      expect(droppedTable.rows[0]?.regclass).toBeNull();

      const rolledBackStatus = await runCli(["status"], env, workspace);
      expect(rolledBackStatus.exitCode).toBe(0);
      expect(rolledBackStatus.stdout).toContain("Total: 0 executed, 1 pending");
    } finally {
      await database.cleanup();
    }
  });

  test("reports a configuration error when database settings are missing", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-config-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["status"],
      {
        DATABASE_URL: "",
        DB_HOST: "",
        DB_PORT: "",
        DB_NAME: "",
        DB_USER: "",
        DB_PASSWORD: "",
        LOG_LEVEL: "error",
      },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain("Missing required database configuration");
  });
});
