import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, readdir, rm, writeFile } from "fs/promises";
import { tmpdir } from "os";
import { join, resolve } from "path";
import { exerciseMigrationLifecycle } from "./utils/cli-smoke";
import { createTemporaryDatabase } from "./utils/test-helper";

const cliEntrypoint = resolve(process.cwd(), "cli.ts");

interface CliResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

const decode = async (stream: ReadableStream<Uint8Array> | null) => {
  if (!stream) {
    return "";
  }

  return await new Response(stream).text();
};

const runCli = async (
  args: string[],
  env: Record<string, string>,
  cwd: string
): Promise<CliResult> => {
  const child = Bun.spawn([process.execPath, cliEntrypoint, ...args], {
    cwd,
    env: {
      ...process.env,
      ...env,
    },
    stdout: "pipe",
    stderr: "pipe",
  });

  const [stdout, stderr, exitCode] = await Promise.all([
    decode(child.stdout),
    decode(child.stderr),
    child.exited,
  ]);

  return { exitCode, stdout, stderr };
};

describe("cli smoke test", () => {
  const cleanupPaths: string[] = [];

  afterEach(async () => {
    for (const path of cleanupPaths.splice(0)) {
      await rm(path, { recursive: true, force: true });
    }
  });

  test("create works without database settings", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-create-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["create", "widgets"],
      {
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "error",
      },
      workspace
    );

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Created");
    expect(result.stderr).toBe("");

    const createdFiles = await readdir(join(workspace, "migrations"));
    expect(createdFiles.some((file) => file.endsWith(".up.sql"))).toBe(true);
    expect(createdFiles.some((file) => file.endsWith(".down.sql"))).toBe(true);
  });

  test("create, up, status, and down work against a fresh database", async () => {
    const database = await createTemporaryDatabase("cli_smoke");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-smoke-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await exerciseMigrationLifecycle({
        runCli: (args) => runCli(args, env, workspace),
        migrationsPath,
        pool: database.pool,
        migrationName: "widgets",
        tableName: "widgets",
        expectEmptyStderr: true,
      });
    } finally {
      await database.cleanup();
    }
  });

  test("reports a configuration error when database settings are missing", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-config-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["status"],
      {
        DATABASE_URL: "",
        DB_HOST: "",
        DB_PORT: "",
        DB_NAME: "",
        DB_USER: "",
        DB_PASSWORD: "",
        LOG_LEVEL: "error",
      },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain("Missing required database configuration");
  });

  test("status --exit-code returns non-zero when migrations are pending and zero when clean", async () => {
    const database = await createTemporaryDatabase("cli_status_exit_code");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-exit-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);

      const createdFiles = await readdir(migrationsPath);
      const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
      const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

      expect(upFile).toBeDefined();
      expect(downFile).toBeDefined();

      const pendingStatus = await runCli(["status", "--exit-code"], env, workspace);
      expect(pendingStatus.exitCode).toBe(1);
      expect(pendingStatus.stdout).toContain("Total: 0 executed, 1 pending");

      await writeFile(
        join(migrationsPath, upFile!),
        `
        CREATE TABLE widgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, downFile!),
        `DROP TABLE IF EXISTS widgets;`
      );

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);
      expect(upResult.stdout).toContain("Executed 1 migration(s)");

      const cleanStatus = await runCli(["status", "--exit-code"], env, workspace);
      expect(cleanStatus.exitCode).toBe(0);
      expect(cleanStatus.stdout).toContain("Total: 1 executed, 0 pending");
    } finally {
      await database.cleanup();
    }
  });

  test("status --quiet suppresses the verbose status sections", async () => {
    const database = await createTemporaryDatabase("cli_status_quiet");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-quiet-"));
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);

      const quietStatus = await runCli(["status", "--quiet"], env, workspace);
      expect(quietStatus.exitCode).toBe(0);
      expect(quietStatus.stdout).not.toContain("Migration Status:");
      expect(quietStatus.stdout).not.toContain("Pending:");
      expect(quietStatus.stdout).not.toContain("Executed:");
      expect(quietStatus.stdout.trim()).toBe("0 executed, 1 pending");
    } finally {
      await database.cleanup();
    }
  });

  test("status --json returns machine-readable status data", async () => {
    const database = await createTemporaryDatabase("cli_status_json");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-json-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);

      const createdFiles = await readdir(migrationsPath);
      const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
      const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

      expect(upFile).toBeDefined();
      expect(downFile).toBeDefined();

      const pendingStatus = await runCli(["status", "--json", "--exit-code"], env, workspace);
      expect(pendingStatus.exitCode).toBe(1);

      const pendingPayload = JSON.parse(pendingStatus.stdout) as {
        executed: Array<{ filename: string; executedAt: string }>;
        pending: Array<{ filename: string }>;
        summary: { executed: number; pending: number };
      };

      expect(pendingPayload.executed).toHaveLength(0);
      expect(pendingPayload.pending).toEqual([{ filename: upFile! }]);
      expect(pendingPayload.summary).toEqual({ executed: 0, pending: 1 });

      await writeFile(
        join(migrationsPath, upFile!),
        `
        CREATE TABLE widgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, downFile!),
        `DROP TABLE IF EXISTS widgets;`
      );

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);

      const cleanStatus = await runCli(["status", "--json"], env, workspace);
      expect(cleanStatus.exitCode).toBe(0);

      const cleanPayload = JSON.parse(cleanStatus.stdout) as {
        executed: Array<{ filename: string; executedAt: string }>;
        pending: Array<{ filename: string }>;
        summary: { executed: number; pending: number };
      };

      expect(cleanPayload.executed).toHaveLength(1);
      expect(cleanPayload.executed[0]?.filename).toBe(upFile!);
      expect(typeof cleanPayload.executed[0]?.executedAt).toBe("string");
      expect(cleanPayload.pending).toHaveLength(0);
      expect(cleanPayload.summary).toEqual({ executed: 1, pending: 0 });
    } finally {
      await database.cleanup();
    }
  });

  test("status rejects combining --json and --quiet", async () => {
    const database = await createTemporaryDatabase("cli_status_json_quiet");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-json-quiet-"));
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const result = await runCli(["status", "--json", "--quiet"], env, workspace);
      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("cannot be combined");
    } finally {
      await database.cleanup();
    }
  });
});
