import { afterEach, describe, expect, setDefaultTimeout, test } from "bun:test";
import { existsSync } from "node:fs";
import {
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import type { ValidationIssue } from "./core/validate-migrations";
import {
  exerciseMigrationLifecycle,
  type CliCommandResult,
} from "./utils/cli-smoke";
import { createTemporaryDatabase } from "./utils/test-helper";
import {
  runTestSubprocess,
  TestSubprocessTimeoutError,
} from "./test-utils/subprocess";

const cliEntrypoint = resolve(process.cwd(), "cli.ts");
type TestDatabase = Awaited<ReturnType<typeof createTemporaryDatabase>>;

interface RunCliOptions {
  entrypoint?: string;
  retryOnTimeout?: boolean;
  timeoutMs?: number;
}

// Database lifecycle tests can exceed Bun's 5-second default on shared CI runners.
// Keep this comfortably below the mutation runner's and workflow's hard limits.
setDefaultTimeout(15_000);

const cliAttemptTimeoutMs = 5_000;
const cliRetryBackoffMs = 200;

const runCli = async (
  args: string[],
  env: Record<string, string>,
  cwd: string,
  options: RunCliOptions = {}
): Promise<CliCommandResult> => {
  const command = [
    process.execPath,
    options.entrypoint ?? cliEntrypoint,
    ...args,
  ];
  const attempts = options.retryOnTimeout ? 2 : 1;

  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await runTestSubprocess(command, {
        cwd,
        env: {
          ...process.env,
          ...env,
        },
        timeoutMs: options.timeoutMs ?? cliAttemptTimeoutMs,
      });
    } catch (error) {
      if (
        !(error instanceof TestSubprocessTimeoutError) ||
        attempt === attempts
      ) {
        throw error;
      }
      console.warn(
        `CLI process timed out; retrying attempt ${attempt + 1}/${attempts}: ` +
          command.join(" ")
      );
      await new Promise((resolve) => setTimeout(resolve, cliRetryBackoffMs));
    }
  }

  throw new Error("CLI process attempt loop completed unexpectedly");
};

const writeMigrationPair = async (
  migrationsPath: string,
  timestamp: string,
  tableName: string
) => {
  await writeFile(
    join(migrationsPath, `${timestamp}_create_${tableName}.up.sql`),
    `
    CREATE TABLE ${tableName} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL
    );
    `
  );
  await writeFile(
    join(migrationsPath, `${timestamp}_create_${tableName}.down.sql`),
    `DROP TABLE IF EXISTS ${tableName};`
  );
};

const tableExists = async (
  database: TestDatabase,
  tableName: string
) => {
  const result = await database.pool.query<{ regclass: string | null }>(
    "SELECT to_regclass($1) AS regclass",
    [`public.${tableName}`]
  );
  return result.rows[0]?.regclass === tableName;
};

describe("cli smoke test", () => {
  const cleanupPaths: string[] = [];

  afterEach(async () => {
    for (const path of cleanupPaths.splice(0)) {
      await rm(path, { recursive: true, force: true });
    }
  });

  test("create works without database settings", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-create-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["create", "widgets"],
      {
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "error",
      },
      workspace
    );

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Created");
    expect(result.stderr).toBe("");

    const createdFiles = await readdir(join(workspace, "migrations"));
    expect(createdFiles.some((file) => file.endsWith(".up.sql"))).toBe(true);
    expect(createdFiles.some((file) => file.endsWith(".down.sql"))).toBe(true);
  });

  test("cli startup path does not statically import pg", async () => {
    const cliSource = await readFile(cliEntrypoint, "utf-8");

    expect(cliSource).not.toContain("from \"pg\"");
  });

  test("init creates the migrations directory without database settings", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-init-local-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["init"],
      {
        DATABASE_URL: "",
        DB_HOST: "",
        DB_PORT: "",
        DB_NAME: "",
        DB_USER: "",
        DB_PASSWORD: "",
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "error",
      },
      workspace
    );

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Created migrations directory: migrations");
    expect(result.stdout).toContain("Next steps:");
    expect(result.stderr).toBe("");
    expect(await readdir(join(workspace, "migrations"))).toEqual([]);
  });

  test("create --json returns machine-readable file data", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-create-json-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["create", "widgets", "--json"],
      {
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "info",
      },
      workspace
    );

    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe("");

    const payload = JSON.parse(result.stdout) as {
      ok: boolean;
      command: string;
      upFile: string;
      downFile: string;
      migrationsPath: string;
    };

    expect(payload.ok).toBe(true);
    expect(payload.command).toBe("create");
    expect(payload.upFile.endsWith(".up.sql")).toBe(true);
    expect(payload.downFile.endsWith(".down.sql")).toBe(true);
    expect(payload.migrationsPath).toBe("migrations");
  });

  test("supports command-scoped help without mutating the project", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-help-"));
    cleanupPaths.push(workspace);
    const env = { MIGRATIONS_PATH: "migrations", LOG_LEVEL: "error" };

    const createHelp = await runCli(["create", "--help"], env, workspace);
    const upHelp = await runCli(["help", "up"], env, workspace);

    expect(createHelp.exitCode).toBe(0);
    expect(createHelp.stdout).toContain("Usage: tusk create <name>");
    expect(upHelp.exitCode).toBe(0);
    expect(upHelp.stdout).toContain("Usage: tusk up");
    await expect(readdir(join(workspace, "migrations"))).rejects.toThrow();
  });

  test("rejects traversal migration names without writing outside migrations", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-name-safety-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["create", "../../../escaped", "--json"],
      { MIGRATIONS_PATH: "migrations", LOG_LEVEL: "error" },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(JSON.parse(result.stdout)).toMatchObject({
      ok: false,
      command: "create",
      error: { code: "VALIDATION_ERROR" },
    });
    expect(await readdir(workspace)).toEqual([]);
  });

  test("prints human errors once without a duplicate timestamped log", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-error-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["unknown"],
      { LOG_LEVEL: "error" },
      workspace,
      { retryOnTimeout: true }
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr.match(/\[VALIDATION_ERROR\]/g)).toHaveLength(1);
    expect(result.stderr).not.toMatch(/\[\d{4}-\d{2}-\d{2}T/);
  });

  test("retries a timed-out CLI process only when explicitly requested", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-retry-"));
    const fixtureEntrypoint = join(workspace, "fixture.ts");
    const attemptsPath = join(workspace, "attempts");
    cleanupPaths.push(workspace);

    await writeFile(
      fixtureEntrypoint,
      `
        import { appendFile, readFile } from "node:fs/promises";
        await appendFile(${JSON.stringify(attemptsPath)}, "attempt\\n");
        const attempts = (await readFile(${JSON.stringify(attemptsPath)}, "utf8"))
          .trim()
          .split("\\n").length;
        if (attempts === 1) await new Promise(() => undefined);
        console.log("completed");
      `
    );

    const result = await runCli([], {}, workspace, {
      entrypoint: fixtureEntrypoint,
      retryOnTimeout: true,
      timeoutMs: 500,
    });

    expect(result).toEqual({
      exitCode: 0,
      stdout: "completed\n",
      stderr: "",
    });
    expect((await readFile(attemptsPath, "utf8")).trim().split("\n"))
      .toHaveLength(2);
  });

  test("does not retry an ordinary CLI failure", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-failure-"));
    const fixtureEntrypoint = join(workspace, "fixture.ts");
    const attemptsPath = join(workspace, "attempts");
    cleanupPaths.push(workspace);

    await writeFile(
      fixtureEntrypoint,
      `
        import { appendFile } from "node:fs/promises";
        await appendFile(${JSON.stringify(attemptsPath)}, "attempt\\n");
        process.exit(1);
      `
    );

    const result = await runCli([], {}, workspace, {
      entrypoint: fixtureEntrypoint,
      retryOnTimeout: true,
      timeoutMs: 500,
    });

    expect(result.exitCode).toBe(1);
    expect((await readFile(attemptsPath, "utf8")).trim().split("\n"))
      .toHaveLength(1);
  });

  test("does not retry or orphan descendants after a default CLI timeout", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-no-retry-"));
    const fixtureEntrypoint = join(workspace, "fixture.ts");
    const attemptsPath = join(workspace, "attempts");
    const descendantReadyPath = join(workspace, "descendant-ready");
    const lateForkPath = join(workspace, "late-fork");
    const orphanMarkerPath = join(workspace, "orphan-marker");
    cleanupPaths.push(workspace);

    await writeFile(
      fixtureEntrypoint,
      `
        import { spawn } from "node:child_process";
        import { appendFile } from "node:fs/promises";
        await appendFile(${JSON.stringify(attemptsPath)}, "attempt\\n");
        spawn(process.execPath, ["-e", ${JSON.stringify(
          `const { spawn } = require("node:child_process"); const fs = require("node:fs"); process.on("SIGTERM", () => { fs.writeFileSync(${JSON.stringify(lateForkPath)}, "forked"); spawn(process.execPath, ["-e", ${JSON.stringify(
            `setTimeout(() => require("node:fs").writeFileSync(${JSON.stringify(orphanMarkerPath)}, "orphan"), 1000)`,
          )}], { stdio: "ignore" }); }); fs.writeFileSync(${JSON.stringify(descendantReadyPath)}, "ready"); setInterval(() => {}, 1000)`,
        )}], { stdio: "ignore" });
        while (!require("node:fs").existsSync(${JSON.stringify(descendantReadyPath)})) {
          await new Promise((resolve) => setTimeout(resolve, 10));
        }
        await new Promise(() => undefined);
      `
    );

    await expect(
      runCli([], {}, workspace, {
        entrypoint: fixtureEntrypoint,
        timeoutMs: 500,
      })
    ).rejects.toThrow("Test subprocess timed out after 500ms");

    expect((await readFile(attemptsPath, "utf8")).trim().split("\n"))
      .toHaveLength(1);
    expect(existsSync(descendantReadyPath)).toBe(true);
    if (process.platform !== "win32") {
      expect(existsSync(lateForkPath)).toBe(true);
    }
    await Bun.sleep(1_200);
    expect(existsSync(orphanMarkerPath)).toBe(false);
  });

  test("doctor --json reports missing database configuration without throwing", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-doctor-json-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    await mkdir(migrationsPath);
    await writeFile(
      join(migrationsPath, "1728123456789_create_widgets.up.sql"),
      "CREATE TABLE widgets (id INTEGER PRIMARY KEY);"
    );
    await writeFile(
      join(migrationsPath, "1728123456789_create_widgets.down.sql"),
      "DROP TABLE IF EXISTS widgets;"
    );

    const result = await runCli(
      ["doctor", "--json"],
      {
        DATABASE_URL: "",
        DB_NAME: "",
        DB_USER: "",
        DB_PASSWORD: "",
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "info",
      },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toBe("");

    const payload = JSON.parse(result.stdout) as {
      ok: boolean;
      result: string;
      command: string;
      checks: Array<{ id: string; status: string }>;
    };

    expect(payload.ok).toBe(false);
    expect(payload.result).toBe("fail");
    expect(payload.command).toBe("doctor");
    expect(payload.checks).toContainEqual(expect.objectContaining({
      id: "database.config",
      status: "fail",
    }));
    expect(payload.checks).toContainEqual(expect.objectContaining({
      id: "migrations.valid",
      status: "pass",
    }));
  });

  test("doctor human output does not show info logs by default", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-doctor-human-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["doctor"],
      {
        DATABASE_URL: "",
        DB_NAME: "",
        DB_USER: "",
        DB_PASSWORD: "",
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "",
      },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(result.stdout).toContain("Tusk Doctor");
    expect(result.stdout).not.toContain("[INFO]");
    expect(result.stderr).toBe("");
  });

  test("create, up, status, and down work against a fresh database", async () => {
    const database = await createTemporaryDatabase("cli_smoke");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-smoke-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await exerciseMigrationLifecycle({
        runCli: (args) => runCli(args, env, workspace),
        migrationsPath,
        pool: database.pool,
        migrationName: "widgets",
        tableName: "widgets",
        expectEmptyStderr: true,
      });
    } finally {
      await database.cleanup();
    }
  });

  test("status is read-only when migration metadata does not exist", async () => {
    const database = await createTemporaryDatabase("cli_status_readonly");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-readonly-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    try {
      await mkdir(migrationsPath);
      await writeMigrationPair(migrationsPath, "1728123456789", "widgets");
      const result = await runCli(
        ["status", "--json"],
        {
          DATABASE_URL: database.connectionString,
          MIGRATIONS_PATH: "migrations",
          LOG_LEVEL: "error",
        },
        workspace
      );

      expect(result.exitCode).toBe(0);
      expect(JSON.parse(result.stdout)).toMatchObject({
        summary: { executed: 0, pending: 1 },
      });
      const metadata = await database.pool.query(
        "SELECT to_regclass('_migrations') AS table_name"
      );
      expect(metadata.rows[0]?.table_name).toBeNull();
    } finally {
      await database.cleanup();
    }
  });

  test("init --from-db --json records the generated baseline as executed", async () => {
    const database = await createTemporaryDatabase("cli_init_baseline");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-init-"));
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "info",
    };

    try {
      await database.pool.query(`
        CREATE TABLE accounts (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          email TEXT NOT NULL UNIQUE
        );
      `);

      const result = await runCli(["init", "--from-db", "--json"], env, workspace);
      expect(result.exitCode).toBe(0);
      expect(result.stderr).toBe("");

      const payload = JSON.parse(result.stdout) as {
        ok: boolean;
        command: string;
        upFile: string;
        downFile: string;
        tableCount: number;
        checksum: string;
        markedAsExecuted: boolean;
        migrationsPath: string;
        fromDb: boolean;
      };

      expect(payload.ok).toBe(true);
      expect(payload.command).toBe("init");
      expect(payload.upFile).toBe("0000000000000_initial.up.sql");
      expect(payload.downFile).toBe("0000000000000_initial.down.sql");
      expect(payload.tableCount).toBe(1);
      expect(payload.checksum).toMatch(/^[a-f0-9]{64}$/);
      expect(payload.markedAsExecuted).toBe(true);
      expect(payload.migrationsPath).toBe("migrations");
      expect(payload.fromDb).toBe(true);

      const status = await runCli(["status", "--json"], env, workspace);
      expect(status.exitCode).toBe(0);

      const statusPayload = JSON.parse(status.stdout) as {
        executed: Array<{ filename: string; executedAt: string }>;
        pending: Array<{ filename: string }>;
        summary: { executed: number; pending: number };
      };

      expect(statusPayload.executed[0]?.filename).toBe(payload.upFile);
      expect(statusPayload.pending).toHaveLength(0);
      expect(statusPayload.summary).toEqual({ executed: 1, pending: 0 });

      const dryRun = await runCli(["up", "--dry-run", "--json"], env, workspace);
      expect(dryRun.exitCode).toBe(0);

      const dryRunPayload = JSON.parse(dryRun.stdout) as {
        summary: { planned: number; total: number; alreadyExecuted: number };
      };

      expect(dryRunPayload.summary).toEqual({
        planned: 0,
        total: 1,
        alreadyExecuted: 1,
      });

      const rollback = await runCli(["down", "1", "--json"], env, workspace);
      expect(rollback.exitCode).toBe(1);

      const rollbackPayload = JSON.parse(rollback.stdout) as {
        ok: boolean;
        error: { code: string; message: string };
      };
      let accountsTable = await database.pool.query<{ regclass: string | null }>(
        `SELECT to_regclass('public.accounts') AS regclass`
      );

      expect(rollbackPayload).toMatchObject({
        ok: false,
        error: {
          code: "VALIDATION_ERROR",
          message: expect.stringMatching(
            /Refusing to roll back the adopted baseline.*--allow-baseline-rollback/
          ),
        },
      });
      expect(accountsTable.rows[0]?.regclass).toBe("accounts");

      const destructivePlan = await runCli(
        ["down", "1", "--dry-run", "--allow-baseline-rollback", "--json"],
        env,
        workspace
      );
      expect(destructivePlan.exitCode).toBe(0);
      expect(JSON.parse(destructivePlan.stdout)).toMatchObject({
        dryRun: true,
        summary: { planned: 1 },
      });

      const destructiveRollback = await runCli(
        ["down", "1", "--allow-baseline-rollback", "--json"],
        env,
        workspace
      );
      expect(destructiveRollback.exitCode).toBe(0);
      expect(JSON.parse(destructiveRollback.stdout)).toMatchObject({
        executed: 1,
        pending: 0,
      });
      accountsTable = await database.pool.query<{ regclass: string | null }>(
        `SELECT to_regclass('public.accounts') AS regclass`
      );
      expect(accountsTable.rows[0]?.regclass).toBeNull();
    } finally {
      await database.cleanup();
    }
  });

  test("down defaults to one rollback and --all rolls back every applied migration", async () => {
    const database = await createTemporaryDatabase("cli_down_default_one");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-default-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "info",
    };

    try {
      await mkdir(migrationsPath);
      await writeFile(
        join(migrationsPath, "0000000000001_widgets.up.sql"),
        `
        CREATE TABLE widgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, "0000000000001_widgets.down.sql"),
        "DROP TABLE IF EXISTS widgets;"
      );
      await writeFile(
        join(migrationsPath, "0000000000002_gadgets.up.sql"),
        `
        CREATE TABLE gadgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, "0000000000002_gadgets.down.sql"),
        "DROP TABLE IF EXISTS gadgets;"
      );

      const upResult = await runCli(["up", "--json"], env, workspace);
      expect(upResult.exitCode).toBe(0);

      const dryRunDefault = await runCli(["down", "--dry-run", "--json"], env, workspace);
      expect(dryRunDefault.exitCode).toBe(0);

      const dryRunDefaultPayload = JSON.parse(dryRunDefault.stdout) as {
        migrations: Array<{ rollbackOf: string }>;
        summary: {
          planned: number;
          rollbackTarget: { mode: string; requestedCount?: number };
        };
      };

      expect(dryRunDefaultPayload.migrations).toHaveLength(1);
      expect(dryRunDefaultPayload.migrations[0]?.rollbackOf).toBe(
        "0000000000002_gadgets.up.sql"
      );
      expect(dryRunDefaultPayload.summary).toMatchObject({
        planned: 1,
        rollbackTarget: {
          mode: "count",
          requestedCount: 1,
        },
      });

      const dryRunAll = await runCli(["down", "--all", "--dry-run", "--json"], env, workspace);
      expect(dryRunAll.exitCode).toBe(0);

      const dryRunAllPayload = JSON.parse(dryRunAll.stdout) as {
        migrations: Array<{ rollbackOf: string }>;
        summary: { planned: number };
      };

      expect(dryRunAllPayload.migrations.map((migration) => migration.rollbackOf)).toEqual([
        "0000000000002_gadgets.up.sql",
        "0000000000001_widgets.up.sql",
      ]);
      expect(dryRunAllPayload.summary.planned).toBe(2);

      const defaultRollback = await runCli(["down", "--json"], env, workspace);
      expect(defaultRollback.exitCode).toBe(0);

      const defaultRollbackPayload = JSON.parse(defaultRollback.stdout) as {
        executed: number;
      };

      expect(defaultRollbackPayload.executed).toBe(1);

      const afterDefault = await runCli(["status", "--json"], env, workspace);
      const afterDefaultPayload = JSON.parse(afterDefault.stdout) as {
        executed: Array<{ filename: string }>;
        pending: Array<{ filename: string }>;
      };
      const widgetsAfterDefault = await database.pool.query<{ regclass: string | null }>(
        "SELECT to_regclass('public.widgets') AS regclass"
      );
      const gadgetsAfterDefault = await database.pool.query<{ regclass: string | null }>(
        "SELECT to_regclass('public.gadgets') AS regclass"
      );

      expect(afterDefaultPayload.executed.map((migration) => migration.filename)).toEqual([
        "0000000000001_widgets.up.sql",
      ]);
      expect(afterDefaultPayload.pending.map((migration) => migration.filename)).toEqual([
        "0000000000002_gadgets.up.sql",
      ]);
      expect(widgetsAfterDefault.rows[0]?.regclass).toBe("widgets");
      expect(gadgetsAfterDefault.rows[0]?.regclass).toBeNull();

      const allRollback = await runCli(["down", "--all", "--json"], env, workspace);
      expect(allRollback.exitCode).toBe(0);

      const allRollbackPayload = JSON.parse(allRollback.stdout) as {
        executed: number;
      };
      const widgetsAfterAll = await database.pool.query<{ regclass: string | null }>(
        "SELECT to_regclass('public.widgets') AS regclass"
      );

      expect(allRollbackPayload.executed).toBe(1);
      expect(widgetsAfterAll.rows[0]?.regclass).toBeNull();
    } finally {
      await database.cleanup();
    }
  });

  test("down rolls back one applied migration with no count", async () => {
    const database = await createTemporaryDatabase("cli_down_one_default");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-one-default-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await mkdir(migrationsPath);
      await writeMigrationPair(migrationsPath, "0000000000001", "widgets");

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);
      expect(await tableExists(database, "widgets")).toBe(true);

      const downResult = await runCli(["down"], env, workspace);
      expect(downResult.exitCode).toBe(0);
      expect(downResult.stdout).toContain("Rolled back 1 migration(s)");
      expect(await tableExists(database, "widgets")).toBe(false);

      const doctor = await runCli(["doctor", "--json"], env, workspace);
      expect(doctor.exitCode).toBe(0);
      expect(JSON.parse(doctor.stdout)).toMatchObject({
        ok: true,
        command: "doctor",
        result: "pass",
      });
    } finally {
      await database.cleanup();
    }
  });

  test("down 1 and down 2 roll back newest applied migrations first", async () => {
    const database = await createTemporaryDatabase("cli_down_count_order");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-count-order-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await mkdir(migrationsPath);
      await writeMigrationPair(migrationsPath, "0000000000001", "widgets");
      await writeMigrationPair(migrationsPath, "0000000000002", "gadgets");
      await writeMigrationPair(migrationsPath, "0000000000003", "doodads");

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);

      const downOne = await runCli(["down", "1", "--json"], env, workspace);
      expect(downOne.exitCode).toBe(0);
      expect(JSON.parse(downOne.stdout)).toMatchObject({
        executed: 1,
        rollbackTarget: {
          mode: "count",
          requestedCount: 1,
          availableRollbackCount: 3,
        },
      });
      expect(await tableExists(database, "widgets")).toBe(true);
      expect(await tableExists(database, "gadgets")).toBe(true);
      expect(await tableExists(database, "doodads")).toBe(false);

      const downTwo = await runCli(["down", "2", "--json"], env, workspace);
      expect(downTwo.exitCode).toBe(0);
      expect(JSON.parse(downTwo.stdout)).toMatchObject({
        executed: 2,
        rollbackTarget: {
          mode: "count",
          requestedCount: 2,
          availableRollbackCount: 2,
        },
      });
      expect(await tableExists(database, "widgets")).toBe(false);
      expect(await tableExists(database, "gadgets")).toBe(false);

      const doctor = await runCli(["doctor", "--json"], env, workspace);
      expect(doctor.exitCode).toBe(0);
      expect(JSON.parse(doctor.stdout)).toMatchObject({
        ok: true,
        command: "doctor",
        result: "pass",
      });
    } finally {
      await database.cleanup();
    }
  });

  test("down --all rolls back all applied migrations", async () => {
    const database = await createTemporaryDatabase("cli_down_all");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-all-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await mkdir(migrationsPath);
      await writeMigrationPair(migrationsPath, "0000000000001", "widgets");
      await writeMigrationPair(migrationsPath, "0000000000002", "gadgets");

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);

      const dryRun = await runCli(["down", "--all", "--dry-run", "--json"], env, workspace);
      expect(dryRun.exitCode).toBe(0);
      const dryRunPayload = JSON.parse(dryRun.stdout) as {
        migrations: Array<{ rollbackOf: string }>;
        summary: {
          planned: number;
          rollbackTarget: { mode: string; availableRollbackCount: number };
        };
      };
      expect(dryRunPayload.summary).toMatchObject({
        planned: 2,
        rollbackTarget: {
          mode: "all",
          availableRollbackCount: 2,
        },
      });
      expect(dryRunPayload.migrations.map((migration) => migration.rollbackOf)).toEqual([
        "0000000000002_create_gadgets.up.sql",
        "0000000000001_create_widgets.up.sql",
      ]);

      const downAll = await runCli(["down", "--all", "--json"], env, workspace);
      expect(downAll.exitCode).toBe(0);
      expect(JSON.parse(downAll.stdout)).toMatchObject({
        executed: 2,
        rollbackTarget: {
          mode: "all",
          availableRollbackCount: 2,
        },
      });
      expect(await tableExists(database, "widgets")).toBe(false);
      expect(await tableExists(database, "gadgets")).toBe(false);
    } finally {
      await database.cleanup();
    }
  });

  test("down exits cleanly when no migrations are applied", async () => {
    const database = await createTemporaryDatabase("cli_down_none");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-none-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await mkdir(migrationsPath);
      await writeMigrationPair(migrationsPath, "0000000000001", "widgets");

      const downResult = await runCli(["down"], env, workspace);
      expect(downResult.exitCode).toBe(0);
      expect(downResult.stdout).toContain("No applied migrations to roll back");
    } finally {
      await database.cleanup();
    }
  });

  test("down rolls back all available migrations when count is larger than applied", async () => {
    const database = await createTemporaryDatabase("cli_down_oversized_count");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-oversized-count-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await mkdir(migrationsPath);
      await writeMigrationPair(migrationsPath, "0000000000001", "widgets");
      await writeMigrationPair(migrationsPath, "0000000000002", "gadgets");

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);

      const downResult = await runCli(["down", "5"], env, workspace);
      expect(downResult.exitCode).toBe(0);
      expect(downResult.stdout).toContain(
        "Requested 5 rollback(s), but only 2 applied migration(s) were available"
      );
      expect(await tableExists(database, "widgets")).toBe(false);
      expect(await tableExists(database, "gadgets")).toBe(false);
    } finally {
      await database.cleanup();
    }
  });

  test("down fails before partial rollback when a required down file is missing", async () => {
    const database = await createTemporaryDatabase("cli_down_missing_file");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-missing-file-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      await mkdir(migrationsPath);
      await writeMigrationPair(migrationsPath, "0000000000001", "widgets");
      await writeMigrationPair(migrationsPath, "0000000000002", "gadgets");

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);

      await rm(
        join(migrationsPath, "0000000000002_create_gadgets.down.sql")
      );

      const downResult = await runCli(["down", "--all"], env, workspace);
      expect(downResult.exitCode).toBe(1);
      expect(downResult.stderr).toContain(
        "Missing rollback migration file: 0000000000002_create_gadgets.down.sql"
      );
      expect(await tableExists(database, "widgets")).toBe(true);
      expect(await tableExists(database, "gadgets")).toBe(true);
    } finally {
      await database.cleanup();
    }
  });

  test("down rejects ambiguous rollback selectors", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-down-validation-"));
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: "",
      DB_HOST: "",
      DB_PORT: "",
      DB_NAME: "",
      DB_USER: "",
      DB_PASSWORD: "",
      LOG_LEVEL: "info",
    };

    const countAndAll = await runCli(["down", "--all", "1", "--json"], env, workspace);
    expect(countAndAll.exitCode).toBe(1);
    expect(countAndAll.stderr).toBe("");

    const countAndAllPayload = JSON.parse(countAndAll.stdout) as {
      ok: boolean;
      command: string;
      error: { code: string; message: string };
    };

    expect(countAndAllPayload.ok).toBe(false);
    expect(countAndAllPayload.command).toBe("down");
    expect(countAndAllPayload.error.code).toBe("VALIDATION_ERROR");
    expect(countAndAllPayload.error.message).toContain("cannot combine --all with a count");

    const unknownOption = await runCli(["down", "--everything", "--json"], env, workspace);
    expect(unknownOption.exitCode).toBe(1);

    const unknownOptionPayload = JSON.parse(unknownOption.stdout) as {
      error: { code: string; message: string };
    };

    expect(unknownOptionPayload.error.code).toBe("VALIDATION_ERROR");
    expect(unknownOptionPayload.error.message).toContain("Unknown down option");

    for (const count of ["0", "-1", "abc"]) {
      const invalidCount = await runCli(["down", count, "--json"], env, workspace);
      expect(invalidCount.exitCode).toBe(1);

      const invalidCountPayload = JSON.parse(invalidCount.stdout) as {
        error: { code: string; message: string };
      };

      expect(invalidCountPayload.error.code).toBe("VALIDATION_ERROR");
      expect(invalidCountPayload.error.message).toContain(
        "Count must be a positive integer"
      );
    }
  });

  test("reports a configuration error when database settings are missing", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-config-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["status"],
      {
        DATABASE_URL: "",
        DB_HOST: "",
        DB_PORT: "",
        DB_NAME: "",
        DB_USER: "",
        DB_PASSWORD: "",
        LOG_LEVEL: "error",
      },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain("Missing required database configuration");
  });

  test("reports configuration errors as JSON when --json is used", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-config-json-"));
    cleanupPaths.push(workspace);

    const result = await runCli(
      ["status", "--json"],
      {
        DATABASE_URL: "",
        DB_HOST: "",
        DB_PORT: "",
        DB_NAME: "",
        DB_USER: "",
        DB_PASSWORD: "",
        LOG_LEVEL: "info",
      },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toBe("");

    const payload = JSON.parse(result.stdout) as {
      ok: boolean;
      command: string;
      error: { code: string; message: string };
    };

    expect(payload.ok).toBe(false);
    expect(payload.command).toBe("status");
    expect(payload.error.code).toBe("CONFIGURATION_ERROR");
    expect(payload.error.message).toContain("Missing required database configuration");
  });

  test("status --exit-code returns non-zero when migrations are pending and zero when clean", async () => {
    const database = await createTemporaryDatabase("cli_status_exit_code");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-exit-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);

      const createdFiles = await readdir(migrationsPath);
      const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
      const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

      expect(upFile).toBeDefined();
      expect(downFile).toBeDefined();

      const pendingStatus = await runCli(["status", "--exit-code"], env, workspace);
      expect(pendingStatus.exitCode).toBe(1);
      expect(pendingStatus.stdout).toContain("Total: 0 executed, 1 pending");

      await writeFile(
        join(migrationsPath, upFile!),
        `
        CREATE TABLE widgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, downFile!),
        `DROP TABLE IF EXISTS widgets;`
      );

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);
      expect(upResult.stdout).toContain("Executed 1 migration(s)");

      const cleanStatus = await runCli(["status", "--exit-code"], env, workspace);
      expect(cleanStatus.exitCode).toBe(0);
      expect(cleanStatus.stdout).toContain("Total: 1 executed, 0 pending");
    } finally {
      await database.cleanup();
    }
  });

  test("status --quiet suppresses the verbose status sections", async () => {
    const database = await createTemporaryDatabase("cli_status_quiet");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-quiet-"));
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);

      const quietStatus = await runCli(["status", "--quiet"], env, workspace);
      expect(quietStatus.exitCode).toBe(0);
      expect(quietStatus.stdout).not.toContain("Migration Status:");
      expect(quietStatus.stdout).not.toContain("Pending:");
      expect(quietStatus.stdout).not.toContain("Executed:");
      expect(quietStatus.stdout.trim()).toBe("0 executed, 1 pending");
    } finally {
      await database.cleanup();
    }
  });

  test("status --json returns machine-readable status data", async () => {
    const database = await createTemporaryDatabase("cli_status_json");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-json-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);

      const createdFiles = await readdir(migrationsPath);
      const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
      const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

      expect(upFile).toBeDefined();
      expect(downFile).toBeDefined();

      const pendingStatus = await runCli(["status", "--json", "--exit-code"], env, workspace);
      expect(pendingStatus.exitCode).toBe(1);

      const pendingPayload = JSON.parse(pendingStatus.stdout) as {
        ok: boolean;
        command: string;
        executed: Array<{ filename: string; executedAt: string }>;
        pending: Array<{ filename: string }>;
        summary: { executed: number; pending: number };
      };

      expect(pendingPayload.ok).toBe(true);
      expect(pendingPayload.command).toBe("status");
      expect(pendingPayload.executed).toHaveLength(0);
      expect(pendingPayload.pending).toEqual([{ filename: upFile! }]);
      expect(pendingPayload.summary).toEqual({ executed: 0, pending: 1 });

      await writeFile(
        join(migrationsPath, upFile!),
        `
        CREATE TABLE widgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, downFile!),
        `DROP TABLE IF EXISTS widgets;`
      );

      const upResult = await runCli(["up"], env, workspace);
      expect(upResult.exitCode).toBe(0);

      const cleanStatus = await runCli(["status", "--json"], env, workspace);
      expect(cleanStatus.exitCode).toBe(0);

      const cleanPayload = JSON.parse(cleanStatus.stdout) as {
        ok: boolean;
        command: string;
        executed: Array<{ filename: string; executedAt: string }>;
        pending: Array<{ filename: string }>;
        summary: { executed: number; pending: number };
      };

      expect(cleanPayload.executed).toHaveLength(1);
      expect(cleanPayload.executed[0]?.filename).toBe(upFile!);
      expect(typeof cleanPayload.executed[0]?.executedAt).toBe("string");
      expect(cleanPayload.pending).toHaveLength(0);
      expect(cleanPayload.summary).toEqual({ executed: 1, pending: 0 });
    } finally {
      await database.cleanup();
    }
  });

  test("validate --json checks migration files without database settings", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-validate-json-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const createResult = await runCli(
      ["create", "widgets"],
      {
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "error",
      },
      workspace
    );
    expect(createResult.exitCode).toBe(0);

    const createdFiles = await readdir(migrationsPath);
    const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
    const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

    expect(upFile).toBeDefined();
    expect(downFile).toBeDefined();

    await writeFile(
      join(migrationsPath, upFile!),
      "CREATE TABLE widgets (id INTEGER PRIMARY KEY);"
    );
    await writeFile(join(migrationsPath, downFile!), "DROP TABLE IF EXISTS widgets;");

    const result = await runCli(
      ["validate", "--json"],
      {
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "info",
      },
      workspace
    );

    expect(result.exitCode).toBe(0);
    expect(result.stderr).toBe("");

    const payload = JSON.parse(result.stdout) as {
      ok: boolean;
      command: string;
      issues: ValidationIssue[];
      summary: { errors: number; warnings: number; files: number };
    };

    expect(payload.ok).toBe(true);
    expect(payload.command).toBe("validate");
    expect(payload.issues).toEqual([]);
    expect(payload.summary).toEqual({
      errors: 0,
      warnings: 0,
      files: 2,
      up: 1,
      down: 1,
    });
  });

  test("validate --json uses the command envelope for validation failures", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-validate-json-fail-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    await mkdir(migrationsPath);
    await writeFile(
      join(migrationsPath, "1728123456789_create_widgets.up.sql"),
      "CREATE TABLE widgets (id INTEGER PRIMARY KEY);"
    );

    const result = await runCli(
      ["validate", "--json"],
      {
        MIGRATIONS_PATH: "migrations",
        LOG_LEVEL: "info",
      },
      workspace
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toBe("");

    const payload = JSON.parse(result.stdout) as {
      ok: boolean;
      command: string;
      issues: ValidationIssue[];
      summary: { errors: number; warnings: number; files: number };
      error?: unknown;
    };

    expect(payload.ok).toBe(false);
    expect(payload.command).toBe("validate");
    expect(payload.error).toBeUndefined();
    expect(payload.summary.errors).toBeGreaterThan(0);
    expect(payload.issues).toContainEqual(expect.objectContaining({
      severity: "error",
    }));
  });

  test("up --dry-run --json returns a plan without applying migrations", async () => {
    const database = await createTemporaryDatabase("cli_up_dry_run_json");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-up-dry-run-json-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: database.connectionString,
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "info",
    };

    try {
      const createResult = await runCli(["create", "widgets"], env, workspace);
      expect(createResult.exitCode).toBe(0);

      const createdFiles = await readdir(migrationsPath);
      const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
      const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

      expect(upFile).toBeDefined();
      expect(downFile).toBeDefined();

      await writeFile(
        join(migrationsPath, upFile!),
        `
        CREATE TABLE widgets (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );
        `
      );
      await writeFile(
        join(migrationsPath, downFile!),
        `DROP TABLE IF EXISTS widgets;`
      );

      const dryRun = await runCli(["up", "--dry-run", "--json"], env, workspace);
      expect(dryRun.exitCode).toBe(0);
      expect(dryRun.stderr).toBe("");

      const payload = JSON.parse(dryRun.stdout) as {
        ok: boolean;
        command: string;
        dryRun: boolean;
        direction: string;
        migrations: Array<{ filename: string; sql: string; checksum: string }>;
        summary: { planned: number; total: number; alreadyExecuted: number };
      };

      expect(payload.ok).toBe(true);
      expect(payload.command).toBe("up");
      expect(payload.dryRun).toBe(true);
      expect(payload.direction).toBe("up");
      expect(payload.migrations).toHaveLength(1);
      expect(payload.migrations[0]?.filename).toBe(upFile!);
      expect(payload.migrations[0]?.sql).toContain("CREATE TABLE widgets");
      expect(payload.summary).toEqual({
        planned: 1,
        total: 1,
        alreadyExecuted: 0,
      });

      const createdTable = await database.pool.query<{ regclass: string | null }>(
        `SELECT to_regclass($1) AS regclass`,
        ["public.widgets"]
      );
      expect(createdTable.rows[0]?.regclass).toBeNull();
    } finally {
      await database.cleanup();
    }
  });

  test("status rejects combining --json and --quiet", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-cli-status-json-quiet-"));
    cleanupPaths.push(workspace);

    const env = {
      DATABASE_URL: "",
      DB_HOST: "",
      DB_PORT: "",
      DB_NAME: "",
      DB_USER: "",
      DB_PASSWORD: "",
      MIGRATIONS_PATH: "migrations",
      LOG_LEVEL: "error",
    };

    const result = await runCli(["status", "--json", "--quiet"], env, workspace);
    expect(result.exitCode).toBe(1);
    expect(result.stderr).toBe("");

    const payload = JSON.parse(result.stdout) as {
      ok: boolean;
      command: string;
      error: { code: string; message: string };
    };

    expect(payload.ok).toBe(false);
    expect(payload.command).toBe("status");
    expect(payload.error.code).toBe("VALIDATION_ERROR");
    expect(payload.error.message).toContain("cannot be combined");
  });
});
