import { afterEach, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, rm, writeFile } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";
import { Elysia } from "elysia";
import { Pool } from "pg";
import { createTemporaryDatabase } from "../utils/test-helper";
import { createPoolHandle, migrate } from "./elysia";

const waitFor = async (check: () => Promise<boolean>, timeoutMs: number = 2_000) => {
  const startedAt = Date.now();

  while (Date.now() - startedAt < timeoutMs) {
    if (await check()) {
      return;
    }

    await Bun.sleep(50);
  }

  throw new Error("Timed out waiting for plugin startup");
};

describe("createPoolHandle", () => {
  const cleanupPaths: string[] = [];

  afterEach(async () => {
    for (const path of cleanupPaths.splice(0)) {
      await rm(path, { recursive: true, force: true });
    }
  });

  test("does not take ownership of a caller-provided pool", () => {
    const pool = {} as Pool;

    const handle = createPoolHandle({ pool });

    expect(handle.pool).toBe(pool);
    expect(handle.ownsPool).toBe(false);
  });

  test("creates and owns a pool from connection config", () => {
    const handle = createPoolHandle({
      connection: {
        host: "localhost",
        port: 5432,
        database: "tusk",
        user: "postgres",
        password: "secret",
      },
    });

    expect(handle.pool).toBeInstanceOf(Pool);
    expect(handle.ownsPool).toBe(true);

    void handle.pool.end();
  });

  test("runs startup migrations in a real Elysia app without closing a caller-owned pool", async () => {
    const database = await createTemporaryDatabase("elysia_smoke");
    const workspace = await mkdtemp(join(tmpdir(), "tusk-elysia-smoke-"));
    const migrationsPath = join(workspace, "migrations");
    cleanupPaths.push(workspace);
    await mkdir(migrationsPath, { recursive: true });

    await writeFile(
      join(migrationsPath, "0000000000001_create_widgets.up.sql"),
      `
      CREATE TABLE plugin_widgets (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
      );
      `
    );
    await writeFile(
      join(migrationsPath, "0000000000001_create_widgets.down.sql"),
      `DROP TABLE IF EXISTS plugin_widgets;`
    );

    let app: Elysia | undefined;

    try {
      app = new Elysia()
        .use(
          migrate({
            pool: database.pool,
            migrationsPath,
          })
        )
        .get("/", () => "ok")
        .listen(0);

      await waitFor(async () => {
        const result = await database.pool.query<{ regclass: string | null }>(
          `SELECT to_regclass('public.plugin_widgets') AS regclass`
        );

        return result.rows[0]?.regclass === "plugin_widgets";
      });

      await app.stop();

      const result = await database.pool.query<{ value: number }>(
        "SELECT 1 AS value"
      );
      expect(result.rows[0]?.value).toBe(1);
    } finally {
      if (app?.server) {
        await app.stop();
      }

      await database.cleanup();
    }
  });
});
