import { describe, expect, setDefaultTimeout, test } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createTemporaryDatabase } from "../utils/test-helper";
import { callMcpTool } from "./test-utils/server";

setDefaultTimeout(15_000);

const createMigrationTable = async (
  database: Awaited<ReturnType<typeof createTemporaryDatabase>>,
) => {
  await database.pool.query(`
    CREATE TABLE _migrations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      filename VARCHAR(255) NOT NULL UNIQUE,
      executed_at TIMESTAMP DEFAULT NOW(),
      checksum VARCHAR(64)
    )
  `);
};

describe("MCP server database safety", () => {
  test("refuses implicit rollback of an adopted baseline", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-mcp-baseline-"));
    const database = await createTemporaryDatabase("mcp_baseline");
    try {
      await writeFile(
        join(workspace, "0000000000000_initial.up.sql"),
        "CREATE TABLE widgets (id INTEGER PRIMARY KEY);",
      );
      await writeFile(
        join(workspace, "0000000000000_initial.down.sql"),
        "DROP TABLE widgets;",
      );
      await createMigrationTable(database);
      await database.pool.query(
        "INSERT INTO _migrations (filename) VALUES ($1)",
        ["0000000000000_initial.up.sql"],
      );

      const response = await callMcpTool(
        "tusk_plan_down",
        { migrationsPath: workspace },
        { DATABASE_URL: database.connectionString },
      );

      expect(response.result.isError).toBe(true);
      expect(response.result.content[0]?.text).toContain(
        "Refusing to roll back the adopted baseline",
      );
    } finally {
      await database.cleanup();
      await rm(workspace, { recursive: true, force: true });
    }
  });

  test("performs checksum validation when database checks are requested", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "tusk-mcp-drift-"));
    const database = await createTemporaryDatabase("mcp_drift");
    const filename = "1728123456789_widgets.up.sql";
    try {
      await writeFile(
        join(workspace, filename),
        "CREATE TABLE widgets (id INTEGER PRIMARY KEY);",
      );
      await writeFile(
        join(workspace, "1728123456789_widgets.down.sql"),
        "DROP TABLE widgets;",
      );
      await createMigrationTable(database);
      await database.pool.query(
        "INSERT INTO _migrations (filename, checksum) VALUES ($1, $2)",
        [filename, "not-the-current-checksum"],
      );

      const response = await callMcpTool(
        "tusk_validate",
        { migrationsPath: workspace, checkDatabase: true },
        { DATABASE_URL: database.connectionString },
      );
      const result = JSON.parse(response.result.content[0]!.text) as {
        ok: boolean;
        issues: Array<{ code: string }>;
      };

      expect(response.result.isError).toBe(false);
      expect(result.ok).toBe(false);
      expect(result.issues.map((issue) => issue.code)).toContain(
        "EXECUTED_MIGRATION_CHECKSUM_MISMATCH",
      );
    } finally {
      await database.cleanup();
      await rm(workspace, { recursive: true, force: true });
    }
  });
});
