import { expect } from "bun:test";
import { readdir, writeFile } from "fs/promises";
import { join } from "path";
import type { Pool } from "pg";
import type {
  DoctorJsonPayload,
  InitialMigrationJsonPayload,
  MigrationCommandJsonPayload,
  MigrationCreateJsonPayload,
  MigrationDryRunJsonPayload,
  MigrationStatusJsonPayload,
  ProjectInitJsonPayload,
  ValidateJsonPayload,
} from "../types/cli.js";

export interface CliCommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

interface ExerciseMigrationLifecycleOptions {
  runCli: (args: string[]) => Promise<CliCommandResult>;
  migrationsPath: string;
  pool: Pool;
  migrationName: string;
  tableName: string;
  expectEmptyStderr?: boolean;
}

interface ExerciseExistingDatabaseAdoptionOptions {
  runCli: (args: string[]) => Promise<CliCommandResult>;
  migrationsPath: string;
  pool: Pool;
  existingTableName: string;
  followUpMigrationName: string;
  followUpTableName: string;
  expectEmptyStderr?: boolean;
}

const parseJsonPayload = <T>(result: CliCommandResult): T =>
  JSON.parse(result.stdout) as T;

const expectJsonResult = <T extends { ok: boolean; command: string }>(
  result: CliCommandResult,
  command: string,
  expectEmptyStderr: boolean
): T => {
  expect(result.exitCode).toBe(0);

  if (expectEmptyStderr) {
    expect(result.stderr).toBe("");
  }

  const payload = parseJsonPayload<T>(result);
  expect(payload.ok).toBe(true);
  expect(payload.command).toBe(command);
  return payload;
};

const expectTableExists = async (pool: Pool, tableName: string) => {
  const result = await pool.query<{ regclass: string | null }>(
    `SELECT to_regclass($1) AS regclass`,
    [`public.${tableName}`]
  );
  expect(result.rows[0]?.regclass).toBe(tableName);
};

const expectTableMissing = async (pool: Pool, tableName: string) => {
  const result = await pool.query<{ regclass: string | null }>(
    `SELECT to_regclass($1) AS regclass`,
    [`public.${tableName}`]
  );
  expect(result.rows[0]?.regclass).toBeNull();
};

export const exerciseMigrationLifecycle = async ({
  runCli,
  migrationsPath,
  pool,
  migrationName,
  tableName,
  expectEmptyStderr = false,
}: ExerciseMigrationLifecycleOptions) => {
  const initPayload = expectJsonResult<ProjectInitJsonPayload>(
    await runCli(["init", "--json"]),
    "init",
    expectEmptyStderr
  );
  expect(initPayload.migrationsPath).toBe("migrations");
  expect(initPayload.created).toBe(true);

  const initialDoctorPayload = expectJsonResult<DoctorJsonPayload>(
    await runCli(["doctor", "--json"]),
    "doctor",
    expectEmptyStderr
  );
  expect(initialDoctorPayload.summary.errors).toBe(0);

  const createPayload = expectJsonResult<MigrationCreateJsonPayload>(
    await runCli(["create", migrationName, "--json"]),
    "create",
    expectEmptyStderr
  );

  expect(createPayload.migrationsPath).toBe("migrations");

  const createdFiles = await readdir(migrationsPath);
  const upFile = createPayload.upFile;
  const downFile = createPayload.downFile;

  expect(createdFiles).toContain(upFile);
  expect(createdFiles).toContain(downFile);

  await writeFile(
    join(migrationsPath, upFile),
    `
    CREATE TABLE ${tableName} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL
    );
    `
  );
  await writeFile(
    join(migrationsPath, downFile),
    `DROP TABLE IF EXISTS ${tableName};`
  );

  const validatePayload = expectJsonResult<ValidateJsonPayload>(
    await runCli(["validate", "--json"]),
    "validate",
    expectEmptyStderr
  );
  expect(validatePayload.summary.errors).toBe(0);
  expect(validatePayload.summary.files).toBe(2);

  const validateDbPayload = expectJsonResult<ValidateJsonPayload>(
    await runCli(["validate", "--db", "--json"]),
    "validate",
    expectEmptyStderr
  );
  expect(validateDbPayload.summary.errors).toBe(0);

  const readyDoctorPayload = expectJsonResult<DoctorJsonPayload>(
    await runCli(["doctor", "--json"]),
    "doctor",
    expectEmptyStderr
  );
  expect(readyDoctorPayload.summary.errors).toBe(0);

  const upDryRunPayload = expectJsonResult<MigrationDryRunJsonPayload<"up">>(
    await runCli(["up", "--dry-run", "--json"]),
    "up",
    expectEmptyStderr
  );
  expect(upDryRunPayload.dryRun).toBe(true);
  expect(upDryRunPayload.direction).toBe("up");
  expect(upDryRunPayload.migrations).toHaveLength(1);
  expect(upDryRunPayload.migrations[0]?.filename).toBe(upFile);
  expect(upDryRunPayload.summary).toEqual({
    planned: 1,
    total: 1,
    alreadyExecuted: 0,
  });
  await expectTableMissing(pool, tableName);

  const upPayload = expectJsonResult<MigrationCommandJsonPayload<"up">>(
    await runCli(["up", "--json"]),
    "up",
    expectEmptyStderr
  );
  expect(upPayload.executed).toBe(1);
  expect(upPayload.pending).toBe(0);
  await expectTableExists(pool, tableName);

  const statusPayload = expectJsonResult<MigrationStatusJsonPayload>(
    await runCli(["status", "--json"]),
    "status",
    expectEmptyStderr
  );
  expect(statusPayload.executed[0]?.filename).toBe(upFile);
  expect(statusPayload.pending).toHaveLength(0);
  expect(statusPayload.summary).toEqual({ executed: 1, pending: 0 });

  const downDryRunPayload = expectJsonResult<MigrationDryRunJsonPayload<"down">>(
    await runCli(["down", "--dry-run", "--json"]),
    "down",
    expectEmptyStderr
  );
  expect(downDryRunPayload.dryRun).toBe(true);
  expect(downDryRunPayload.direction).toBe("down");
  expect(downDryRunPayload.migrations).toHaveLength(1);
  expect(downDryRunPayload.migrations[0]?.rollbackOf).toBe(upFile);
  expect(downDryRunPayload.summary.rollbackTarget).toEqual({
    mode: "count",
    requestedCount: 1,
    availableRollbackCount: 1,
  });
  await expectTableExists(pool, tableName);

  const downPayload = expectJsonResult<MigrationCommandJsonPayload<"down">>(
    await runCli(["down", "1", "--json"]),
    "down",
    expectEmptyStderr
  );
  expect(downPayload.executed).toBe(1);
  expect(downPayload.pending).toBe(0);
  expect(downPayload.rollbackTarget).toEqual({
    mode: "count",
    requestedCount: 1,
    availableRollbackCount: 1,
  });
  await expectTableMissing(pool, tableName);

  const rolledBackStatus = expectJsonResult<MigrationStatusJsonPayload>(
    await runCli(["status", "--json"]),
    "status",
    expectEmptyStderr
  );
  expect(rolledBackStatus.executed).toHaveLength(0);
  expect(rolledBackStatus.pending[0]?.filename).toBe(upFile);
  expect(rolledBackStatus.summary).toEqual({ executed: 0, pending: 1 });

  const finalDoctorPayload = expectJsonResult<DoctorJsonPayload>(
    await runCli(["doctor", "--json"]),
    "doctor",
    expectEmptyStderr
  );
  expect(finalDoctorPayload.summary.errors).toBe(0);

  return { upFile, downFile };
};

export const exerciseExistingDatabaseAdoption = async ({
  runCli,
  migrationsPath,
  pool,
  existingTableName,
  followUpMigrationName,
  followUpTableName,
  expectEmptyStderr = false,
}: ExerciseExistingDatabaseAdoptionOptions) => {
  await pool.query(`
    CREATE TABLE ${existingTableName} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL
    );
  `);

  const initPayload = expectJsonResult<InitialMigrationJsonPayload>(
    await runCli(["init", "--from-db", "--json"]),
    "init",
    expectEmptyStderr
  );
  expect(initPayload.fromDb).toBe(true);
  expect(initPayload.markedAsExecuted).toBe(true);
  expect(initPayload.tableCount).toBe(1);
  expect(initPayload.upFile).toBe("0000000000000_initial.up.sql");
  expect(initPayload.downFile).toBe("0000000000000_initial.down.sql");
  expect(initPayload.migrationsPath).toBe("migrations");

  const adoptedFiles = await readdir(migrationsPath);
  expect(adoptedFiles).toContain(initPayload.upFile);
  expect(adoptedFiles).toContain(initPayload.downFile);

  const adoptedStatusPayload = expectJsonResult<MigrationStatusJsonPayload>(
    await runCli(["status", "--json"]),
    "status",
    expectEmptyStderr
  );
  expect(adoptedStatusPayload.executed[0]?.filename).toBe(initPayload.upFile);
  expect(adoptedStatusPayload.pending).toHaveLength(0);
  expect(adoptedStatusPayload.summary).toEqual({ executed: 1, pending: 0 });

  const baselineDryRunPayload = expectJsonResult<MigrationDryRunJsonPayload<"up">>(
    await runCli(["up", "--dry-run", "--json"]),
    "up",
    expectEmptyStderr
  );
  expect(baselineDryRunPayload.summary).toEqual({
    planned: 0,
    total: 1,
    alreadyExecuted: 1,
  });

  const createPayload = expectJsonResult<MigrationCreateJsonPayload>(
    await runCli(["create", followUpMigrationName, "--json"]),
    "create",
    expectEmptyStderr
  );

  await writeFile(
    join(migrationsPath, createPayload.upFile),
    `
    CREATE TABLE ${followUpTableName} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      adopted_id INTEGER NOT NULL REFERENCES ${existingTableName}(id)
    );
    `
  );
  await writeFile(
    join(migrationsPath, createPayload.downFile),
    `DROP TABLE IF EXISTS ${followUpTableName};`
  );

  const validateDbPayload = expectJsonResult<ValidateJsonPayload>(
    await runCli(["validate", "--db", "--json"]),
    "validate",
    expectEmptyStderr
  );
  expect(validateDbPayload.summary.errors).toBe(0);

  const upPayload = expectJsonResult<MigrationCommandJsonPayload<"up">>(
    await runCli(["up", "--json"]),
    "up",
    expectEmptyStderr
  );
  expect(upPayload.executed).toBe(1);
  expect(upPayload.pending).toBe(0);
  await expectTableExists(pool, existingTableName);
  await expectTableExists(pool, followUpTableName);

  const downDryRunPayload = expectJsonResult<MigrationDryRunJsonPayload<"down">>(
    await runCli(["down", "--dry-run", "--json"]),
    "down",
    expectEmptyStderr
  );
  expect(downDryRunPayload.summary.rollbackTarget).toEqual({
    mode: "count",
    requestedCount: 1,
    availableRollbackCount: 2,
  });
  await expectTableExists(pool, followUpTableName);

  const downPayload = expectJsonResult<MigrationCommandJsonPayload<"down">>(
    await runCli(["down", "--json"]),
    "down",
    expectEmptyStderr
  );
  expect(downPayload.rollbackTarget).toEqual({
    mode: "count",
    requestedCount: 1,
    availableRollbackCount: 2,
  });
  await expectTableExists(pool, existingTableName);
  await expectTableMissing(pool, followUpTableName);

  return {
    baselineUpFile: initPayload.upFile,
    followUpUpFile: createPayload.upFile,
  };
};
