import { expect } from "bun:test";
import { readdir, writeFile } from "fs/promises";
import { join } from "path";
import type { Pool } from "pg";

export interface CliCommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

interface ExerciseMigrationLifecycleOptions {
  runCli: (args: string[]) => Promise<CliCommandResult>;
  migrationsPath: string;
  pool: Pool;
  migrationName: string;
  tableName: string;
  expectEmptyStderr?: boolean;
}

export const exerciseMigrationLifecycle = async ({
  runCli,
  migrationsPath,
  pool,
  migrationName,
  tableName,
  expectEmptyStderr = false,
}: ExerciseMigrationLifecycleOptions) => {
  const createResult = await runCli(["create", migrationName]);
  expect(createResult.exitCode).toBe(0);
  expect(createResult.stdout).toContain("Created");

  if (expectEmptyStderr) {
    expect(createResult.stderr).toBe("");
  }

  const createdFiles = await readdir(migrationsPath);
  const upFile = createdFiles.find((file) => file.endsWith(".up.sql"));
  const downFile = createdFiles.find((file) => file.endsWith(".down.sql"));

  expect(upFile).toBeDefined();
  expect(downFile).toBeDefined();

  await writeFile(
    join(migrationsPath, upFile!),
    `
    CREATE TABLE ${tableName} (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL
    );
    `
  );
  await writeFile(
    join(migrationsPath, downFile!),
    `DROP TABLE IF EXISTS ${tableName};`
  );

  const upResult = await runCli(["up"]);
  expect(upResult.exitCode).toBe(0);
  expect(upResult.stdout).toContain("Executed 1 migration(s)");

  const createdTable = await pool.query<{ regclass: string | null }>(
    `SELECT to_regclass($1) AS regclass`,
    [`public.${tableName}`]
  );
  expect(createdTable.rows[0]?.regclass).toBe(tableName);

  const statusResult = await runCli(["status"]);
  expect(statusResult.exitCode).toBe(0);
  expect(statusResult.stdout).toContain(upFile!);
  expect(statusResult.stdout).toContain("Total: 1 executed, 0 pending");

  const downResult = await runCli(["down", "1"]);
  expect(downResult.exitCode).toBe(0);
  expect(downResult.stdout).toContain("Rolled back 1 migration(s)");

  const droppedTable = await pool.query<{ regclass: string | null }>(
    `SELECT to_regclass($1) AS regclass`,
    [`public.${tableName}`]
  );
  expect(droppedTable.rows[0]?.regclass).toBeNull();

  const rolledBackStatus = await runCli(["status"]);
  expect(rolledBackStatus.exitCode).toBe(0);
  expect(rolledBackStatus.stdout).toContain("Total: 0 executed, 1 pending");

  return { upFile, downFile };
};
