import { describe, expect, test } from "bun:test";
import type { ColumnInfo, TableInfo } from "../../types/schema";
import {
  columnToSQL,
  generateCreateTable,
  generateDropTable,
  generateUpMigration,
} from "./sql-generator";

describe("sql-generator", () => {
  const baseColumn = (overrides: Partial<ColumnInfo>): ColumnInfo => ({
    name: "value",
    type: "text",
    isNullable: true,
    defaultValue: null,
    characterMaximumLength: null,
    numericPrecision: null,
    numericScale: null,
    udtName: "text",
    ...overrides,
  });

  test("renders identity columns explicitly", () => {
    const column: ColumnInfo = {
      name: "id",
      type: "integer",
      isNullable: false,
      defaultValue: null,
      characterMaximumLength: null,
      numericPrecision: null,
      numericScale: null,
      udtName: "int4",
      isIdentity: true,
      identityGeneration: "BY DEFAULT",
    };

    expect(columnToSQL(column)).toBe(
      "\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    );
  });

  test("normalizes common PostgreSQL column types", () => {
    expect(
      columnToSQL(
        baseColumn({
          name: "email",
          type: "character varying",
          characterMaximumLength: 255,
          isNullable: false,
        })
      )
    ).toBe("\"email\" VARCHAR(255) NOT NULL");

    expect(
      columnToSQL(
        baseColumn({
          name: "nickname",
          type: "character varying",
        })
      )
    ).toBe("\"nickname\" VARCHAR");

    expect(
      columnToSQL(
        baseColumn({
          name: "price",
          type: "numeric",
          numericPrecision: 10,
          numericScale: 2,
        })
      )
    ).toBe("\"price\" NUMERIC(10, 2)");

    expect(
      columnToSQL(
        baseColumn({
          name: "quantity",
          type: "numeric",
          numericPrecision: 12,
          numericScale: 0,
        })
      )
    ).toBe("\"quantity\" NUMERIC(12)");

    expect(
      columnToSQL(
        baseColumn({
          name: "ratio",
          type: "numeric",
        })
      )
    ).toBe("\"ratio\" NUMERIC");

    expect(
      columnToSQL(
        baseColumn({
          name: "created_at",
          type: "timestamp with time zone",
        })
      )
    ).toBe("\"created_at\" TIMESTAMPTZ");

    expect(
      columnToSQL(
        baseColumn({
          name: "scheduled_for",
          type: "timestamp without time zone",
        })
      )
    ).toBe("\"scheduled_for\" TIMESTAMP");
  });

  test("normalizes default values and skips serial defaults", () => {
    expect(
      columnToSQL(
        baseColumn({
          name: "id",
          type: "integer",
          defaultValue: "nextval('widgets_id_seq'::regclass)",
          isNullable: false,
        })
      )
    ).toBe("\"id\" SERIAL NOT NULL");

    expect(
      columnToSQL(
        baseColumn({
          name: "active",
          type: "boolean",
          defaultValue: "false",
        })
      )
    ).toBe("\"active\" BOOLEAN DEFAULT FALSE");

    expect(
      columnToSQL(
        baseColumn({
          name: "created_at",
          type: "timestamp with time zone",
          defaultValue: "now()",
        })
      )
    ).toBe("\"created_at\" TIMESTAMPTZ DEFAULT NOW()");

    expect(
      columnToSQL(
        baseColumn({
          name: "token",
          type: "uuid",
          defaultValue: "GEN_RANDOM_UUID()",
        })
      )
    ).toBe("\"token\" UUID DEFAULT gen_random_uuid()");
  });

  test("quotes and schema-qualifies generated create table SQL", () => {
    const table: TableInfo = {
      schema: "tenant-data",
      name: "order",
      columns: [
        {
          name: "id",
          type: "integer",
          isNullable: false,
          defaultValue: null,
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
          isIdentity: true,
          identityGeneration: "ALWAYS",
        },
        {
          name: "order_id",
          type: "integer",
          isNullable: false,
          defaultValue: null,
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
        },
      ],
      primaryKeys: [{ columnName: "id", position: 1 }],
      foreignKeys: [
        {
          columnName: "order_id",
          foreignSchema: "tenant-data",
          foreignTableName: "order",
          foreignColumnName: "id",
          updateRule: "NO ACTION",
          deleteRule: "CASCADE",
          constraintName: "order_fk",
        },
      ],
      uniqueConstraints: [],
      indexes: [],
    };

    const sql = generateCreateTable(table);

    expect(sql).toContain("CREATE TABLE \"tenant-data\".\"order\"");
    expect(sql).toContain("\"id\" INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL");
    expect(sql).toContain("PRIMARY KEY (\"id\")");
    expect(sql).toContain(
      "FOREIGN KEY (\"order_id\") REFERENCES \"tenant-data\".\"order\"(\"id\") ON DELETE CASCADE"
    );
  });

  test("preserves cross-schema foreign key references", () => {
    const table: TableInfo = {
      schema: "tenant",
      name: "orders",
      columns: [
        {
          name: "id",
          type: "integer",
          isNullable: false,
          defaultValue: "nextval('orders_id_seq'::regclass)",
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
        },
        {
          name: "account_id",
          type: "integer",
          isNullable: false,
          defaultValue: null,
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
        },
      ],
      primaryKeys: [{ columnName: "id", position: 1 }],
      foreignKeys: [
        {
          columnName: "account_id",
          foreignSchema: "public",
          foreignTableName: "accounts",
          foreignColumnName: "id",
          updateRule: "NO ACTION",
          deleteRule: "CASCADE",
          constraintName: "orders_account_id_fkey",
        },
      ],
      uniqueConstraints: [],
      indexes: [],
    };

    expect(generateCreateTable(table)).toContain(
      'FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE'
    );
  });

  test("emits useful indexes while skipping duplicate unique indexes", () => {
    const table: TableInfo = {
      schema: "public",
      name: "widgets",
      columns: [
        baseColumn({
          name: "id",
          type: "integer",
          isNullable: false,
        }),
        baseColumn({
          name: "slug",
          type: "text",
          isNullable: false,
        }),
        baseColumn({
          name: "created_at",
          type: "timestamp with time zone",
          isNullable: false,
        }),
      ],
      primaryKeys: [{ columnName: "id", position: 1 }],
      foreignKeys: [],
      uniqueConstraints: [
        {
          constraintName: "widgets_slug_key",
          columnNames: ["slug"],
        },
      ],
      indexes: [
        {
          indexName: "widgets_slug_key",
          indexDefinition:
            "CREATE UNIQUE INDEX widgets_slug_key ON public.widgets USING btree (slug)",
        },
        {
          indexName: "widgets_created_at_idx",
          indexDefinition:
            "CREATE INDEX widgets_created_at_idx ON public.widgets USING btree (created_at)",
        },
      ],
    };

    const sql = generateUpMigration({ tables: [table] });

    expect(sql).toContain("CREATE TABLE \"public\".\"widgets\"");
    expect(sql).not.toContain("CREATE UNIQUE INDEX widgets_slug_key");
    expect(sql).toContain(
      "CREATE INDEX widgets_created_at_idx ON widgets (created_at);"
    );
  });

  test("quotes and schema-qualifies drop table SQL", () => {
    expect(generateDropTable("order", "tenant-data")).toBe(
      "DROP TABLE IF EXISTS \"tenant-data\".\"order\" CASCADE;"
    );
  });
});
