import { describe, expect, test } from "bun:test";
import type { ColumnInfo, TableInfo } from "../../types/schema";
import { columnToSQL, generateCreateTable, generateDropTable } from "./sql-generator";

describe("sql-generator", () => {
  test("renders identity columns explicitly", () => {
    const column: ColumnInfo = {
      name: "id",
      type: "integer",
      isNullable: false,
      defaultValue: null,
      characterMaximumLength: null,
      numericPrecision: null,
      numericScale: null,
      udtName: "int4",
      isIdentity: true,
      identityGeneration: "BY DEFAULT",
    };

    expect(columnToSQL(column)).toBe(
      "\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    );
  });

  test("quotes and schema-qualifies generated create table SQL", () => {
    const table: TableInfo = {
      schema: "tenant-data",
      name: "order",
      columns: [
        {
          name: "id",
          type: "integer",
          isNullable: false,
          defaultValue: null,
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
          isIdentity: true,
          identityGeneration: "ALWAYS",
        },
        {
          name: "order_id",
          type: "integer",
          isNullable: false,
          defaultValue: null,
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
        },
      ],
      primaryKeys: [{ columnName: "id", position: 1 }],
      foreignKeys: [
        {
          columnName: "order_id",
          foreignSchema: "tenant-data",
          foreignTableName: "order",
          foreignColumnName: "id",
          updateRule: "NO ACTION",
          deleteRule: "CASCADE",
          constraintName: "order_fk",
        },
      ],
      uniqueConstraints: [],
      indexes: [],
    };

    const sql = generateCreateTable(table);

    expect(sql).toContain("CREATE TABLE \"tenant-data\".\"order\"");
    expect(sql).toContain("\"id\" INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL");
    expect(sql).toContain("PRIMARY KEY (\"id\")");
    expect(sql).toContain(
      "FOREIGN KEY (\"order_id\") REFERENCES \"tenant-data\".\"order\"(\"id\") ON DELETE CASCADE"
    );
  });

  test("preserves cross-schema foreign key references", () => {
    const table: TableInfo = {
      schema: "tenant",
      name: "orders",
      columns: [
        {
          name: "id",
          type: "integer",
          isNullable: false,
          defaultValue: "nextval('orders_id_seq'::regclass)",
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
        },
        {
          name: "account_id",
          type: "integer",
          isNullable: false,
          defaultValue: null,
          characterMaximumLength: null,
          numericPrecision: null,
          numericScale: null,
          udtName: "int4",
        },
      ],
      primaryKeys: [{ columnName: "id", position: 1 }],
      foreignKeys: [
        {
          columnName: "account_id",
          foreignSchema: "public",
          foreignTableName: "accounts",
          foreignColumnName: "id",
          updateRule: "NO ACTION",
          deleteRule: "CASCADE",
          constraintName: "orders_account_id_fkey",
        },
      ],
      uniqueConstraints: [],
      indexes: [],
    };

    expect(generateCreateTable(table)).toContain(
      'FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE'
    );
  });

  test("quotes and schema-qualifies drop table SQL", () => {
    expect(generateDropTable("order", "tenant-data")).toBe(
      "DROP TABLE IF EXISTS \"tenant-data\".\"order\" CASCADE;"
    );
  });
});
